### ISSUE TITLE
Javascript syntax highlighting?

### ISSUE THREAD

**Issue by pwFoo** [romanrehacek/theia-php-docker#1]
Hi @romanrehacek ,

first thanks for sharing your dockerfile with php support / extension! Great work!

It includes php, html and css syntax highlighting, but could be javascript added to be prepared for web projects with all the parts?

**Comment by romanrehacek** [comment]
Hi @pwFoo ,

thanks for reporting this issue.
JS syntax highlighting is fixed now.

**Comment by pwFoo** [comment]
Works fine now 👍
